name = "create-svelte-pages"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-10-22"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "create-svelte-pages"
database_id = "ffcd15cd-a297-4df2-ae4c-a6ca70e3e047"
migrations_dir = "./migrations"
